export const CHARACTERS = 'CHARACTERS';
export const EPISODES = 'EPISODES';
export const LOCATIONS = 'LOCATIONS';
export const SETTINGS = 'SETTINGS';
export const TABNAVIGATOR = 'TABNAVIGATOR';
export const CHARACTERDETAIL = 'CHARACTER DETAIL';
export const FILTERCHARACTERS = 'FILTER  CHARACTERS';
export const SEARCHCHARACTERS = 'SEARCH  CHARACTERS';
